cluster.name: "docker-cluster"
network.host: _eth0:ipv4_
http.cors.enabled: true
http.cors.allow-origin: "*"
node.name: ${ES_HOSTNAME}

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1
