version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=tasks.elasticsearch"
    deploy:
      endpoint_mode: dnsrr
      replicas: 3
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnet
    configs:
      - source: esconfig
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: eslogging
        target: /usr/share/elasticsearch/config/log4j2.properties
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.1
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - esnet
    ports:
      - 5601:5601



volumes:
  esdata:
    driver: local

configs:
  esconfig:
    file: ./elasticsearch-config.yml
  eslogging:
    file: ./elasticsearch-log4j2.properties

networks:
  esnet:

