version: '3.3'

services:
  etcd0:
    image: quay.io/coreos/etcd
    command:
      - "etcd"
      - "--name"
      - "etcd0"
      - "--advertise-client-urls"
      - "http://etcd0:2379"
      - "--listen-client-urls"
      - "http://0.0.0.0:2379"
      - "--initial-advertise-peer-urls"
      - "http://etcd0:2380"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2380"
      - "--initial-cluster-token"
      - "etcd-cluster-0"
      - "--initial-cluster"
      - "etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380"
      - "--initial-cluster-state"
      - "new"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    networks:
      - etcd

  etcd1:
    image: quay.io/coreos/etcd
    command:
      - "etcd"
      - "--name"
      - "etcd1"
      - "--advertise-client-urls"
      - "http://etcd1:2379"
      - "--listen-client-urls"
      - "http://0.0.0.0:2379"
      - "--initial-advertise-peer-urls"
      - "http://etcd1:2380"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2380"
      - "--initial-cluster-token"
      - "etcd-cluster-0"
      - "--initial-cluster"
      - "etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380"
      - "--initial-cluster-state"
      - "new"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    networks:
      - etcd

  etcd2:
    image: quay.io/coreos/etcd
    command:
      - "etcd"
      - "--name"
      - "etcd2"
      - "--advertise-client-urls"
      - "http://etcd2:2379"
      - "--listen-client-urls"
      - "http://0.0.0.0:2379"
      - "--initial-advertise-peer-urls"
      - "http://etcd2:2380"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2380"
      - "--initial-cluster-token"
      - "etcd-cluster-0"
      - "--initial-cluster"
      - "etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380"
      - "--initial-cluster-state"
      - "new"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    networks:
      - etcd


networks:
  etcd:



