version: '3.3'

services:
  kafka1:
    image: confluentinc/cp-kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager
    networks:
      net:
    hostname: "{{.Service.Name}}"
  kafka2:
    image: confluentinc/cp-kafka
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager
    networks:
      net:
    hostname: "{{.Service.Name}}"
  zookeeper1:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager
    networks:
      net:
    hostname: "{{.Service.Name}}"
  zookeeper2:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_SERVER_ID=2
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager
    networks:
      net:
    hostname: "{{.Service.Name}}"
  zookeeper3:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_SERVER_ID=3
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager
    networks:
      net:
    hostname: "{{.Service.Name}}"

networks:
  net:
    driver: overlay
    driver_opts:
      encrypted: "true"

