version: '3.3'

services:
  portainer:
    image: portainer/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: --admin-password-file '/run/secrets/portainer-pass' -H unix:///var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
    ports:
      - "9000:9000"
    secrets:
      - source: portainer-pass
        target: portainer-pass

secrets:
  portainer-pass:
    file: ./portainer-pass.txt

